import "./globals.css";
import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import { Croissant_One } from "next/font/google";
export const croissant = Croissant_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-croissant",
});
export const kanit = Kanit({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${kanit.className}
         min-h-[300vh] className="scroll-smooth" py-5 overflow-x-hidden bg-[#186F65] text-white `}
      >
        {children}
      </body>
    </html>
  );
}
